### ISSUE TITLE
发现一个在新版本vscode上的bug

### ISSUE THREAD

**Issue by moheng233** [Yesterday17/ZenScript#28]
大概是安装插件之后完全没有用吧

```
(node:15192) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of null
    at Function.<anonymous> (c:\Users\Administrator\.vscode\extensions\yesterday17.zenscript-0.2.4\out\server\services\zsDocumentContentChange.js:37:64)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\Administrator\.vscode\extensions\yesterday17.zenscript-0.2.4\out\server\services\zsDocumentContentChange.js:5:58)
(node:15192) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of null
    at Function.<anonymous> (c:\Users\Administrator\.vscode\extensions\yesterday17.zenscript-0.2.4\out\server\services\zsDocumentContentChange.js:37:64)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\Administrator\.vscode\extensions\yesterday17.zenscript-0.2.4\out\server\services\zsDocumentContentChange.js:5:58)
(node:15192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15192) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of null
    at Function.<anonymous> (c:\Users\Administrator\.vscode\extensions\yesterday17.zenscript-0.2.4\out\server\services\zsDocumentContentChange.js:37:64)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\Administrator\.vscode\extensions\yesterday17.zenscript-0.2.4\out\server\services\zsDocumentContentChange.js:5:58)
(node:15192) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of null
    at Function.<anonymous> (c:\Users\Administrator\.vscode\extensions\yesterday17.zenscript-0.2.4\out\server\services\zsDocumentContentChange.js:37:64)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\Administrator\.vscode\extensions\yesterday17.zenscript-0.2.4\out\server\services\zsDocumentContentChange.js:5:58)
(node:15192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by Yesterday17** [comment]
是打开单个文件的问题吗

**Comment by Yesterday17** [comment]
试一下刚更新的 v0.2.5?
