### ISSUE TITLE
Unhandled method zenScript/fsReadDirectory

### ISSUE THREAD

**Issue by CoolRainLy** [Yesterday17/ZenScript#60]
[Error - 02:34:36] Request zenScript/fsReadDirectory failed with message: Error: The "path" argument must be of type string. Received type undefined
c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449
                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                               ^

ResponseError: Request zenScript/fsReadDirectory failed with message: Error: The "path" argument must be of type string. Received type undefined
    at handleResponse (c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449:48)
    at processMessageQueue (c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:276:17)
    at Immediate.<anonymous> (c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:260:13)
    at process.processImmediate (node:internal/timers:466:21) {
  code: -32603,
  data: undefined
}
[Info  - 02:34:36] Connection to server got closed. Server will restart.
[Error - 02:34:37] Unhandled method zenScript/fsReadDirectory
c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449
                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                               ^

ResponseError: Unhandled method zenScript/fsReadDirectory
    at handleResponse (c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449:48)
    at processMessageQueue (c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:276:17)
    at Immediate.<anonymous> (c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:260:13)
    at process.processImmediate (node:internal/timers:466:21) {
  code: -32601,
  data: undefined
}
[Info  - 02:34:37] Connection to server got closed. Server will restart.
[Error - 02:34:37] Unhandled method zenScript/fsReadDirectory
c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449
                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                               ^

ResponseError: Unhandled method zenScript/fsReadDirectory
    at handleResponse (c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449:48)
    at processMessageQueue (c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:276:17)
    at Immediate.<anonymous> (c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:260:13)
    at process.processImmediate (node:internal/timers:466:21) {
  code: -32601,
  data: undefined
}
[Info  - 02:34:37] Connection to server got closed. Server will restart.
[Error - 02:34:38] Unhandled method zenScript/fsReadDirectory
c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449
                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                               ^

ResponseError: Unhandled method zenScript/fsReadDirectory
    at handleResponse (c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449:48)
    at processMessageQueue (c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:276:17)
    at Immediate.<anonymous> (c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:260:13)
    at process.processImmediate (node:internal/timers:466:21) {
  code: -32601,
  data: undefined
}
[Info  - 02:34:38] Connection to server got closed. Server will restart.
[Error - 02:34:38] Unhandled method zenScript/fsReadDirectory
c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449
                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                               ^

ResponseError: Unhandled method zenScript/fsReadDirectory
    at handleResponse (c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449:48)
    at processMessageQueue (c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:276:17)
    at Immediate.<anonymous> (c:\Users\13723\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:260:13)
    at process.processImmediate (node:internal/timers:466:21) {
  code: -32601,
  data: undefined
}
[Error - 02:34:38] Connection to server got closed. Server will not be restarted.

**Comment by mapokapo** [comment]
Getting the same error. Details:

- Using Prism Launcher 7.2 (fork of MultiMC)
- Tried opening either the .minecraft folder or the scripts folder inside .minecraft, same error
- Tried reinstalling extension, renaming instance folder to exclude spaces, and clearing cache, same error
