### ISSUE TITLE
Vscode not connecting to server

### ISSUE THREAD

**Issue by Brunnosh** [Yesterday17/ZenScript#61]
basically that's it, when i open my scripts folder, the extension doesn't connect to the server and does not work for anything, not even simple snippets.
![Screenshot_15](https://github.com/Yesterday17/ZenScript/assets/13407907/e045163f-8100-4aad-87f9-4d66812d4bbd)
---------------------
all of my VsCode output tab:
[Error - 8:16:16 PM] Request zenScript/fsReadDirectory failed with message: Error: The "path" argument must be of type string. Received type undefined
c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449
                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                               ^

ResponseError: Request zenScript/fsReadDirectory failed with message: Error: The "path" argument must be of type string. Received type undefined
    at handleResponse (c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449:48)
    at processMessageQueue (c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:276:17)
    at Immediate.<anonymous> (c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:260:13)
    at process.processImmediate (node:internal/timers:476:21) {
  code: -32603,
  data: undefined
}

Node.js v18.15.0
[Info  - 8:16:16 PM] Connection to server got closed. Server will restart.
[Error - 8:16:17 PM] Unhandled method zenScript/fsReadDirectory
c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449
                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                               ^

ResponseError: Unhandled method zenScript/fsReadDirectory
    at handleResponse (c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449:48)
    at processMessageQueue (c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:276:17)
    at Immediate.<anonymous> (c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:260:13)
    at process.processImmediate (node:internal/timers:476:21) {
  code: -32601,
  data: undefined
}

Node.js v18.15.0
[Info  - 8:16:17 PM] Connection to server got closed. Server will restart.
[Error - 8:16:17 PM] Unhandled method zenScript/fsReadDirectory
c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449
                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                               ^

ResponseError: Unhandled method zenScript/fsReadDirectory
    at handleResponse (c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449:48)
    at processMessageQueue (c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:276:17)
    at Immediate.<anonymous> (c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:260:13)
    at process.processImmediate (node:internal/timers:476:21) {
  code: -32601,
  data: undefined
}

Node.js v18.15.0
[Info  - 8:16:17 PM] Connection to server got closed. Server will restart.
[Error - 8:16:17 PM] Unhandled method zenScript/fsReadDirectory
c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449
                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                               ^

ResponseError: Unhandled method zenScript/fsReadDirectory
    at handleResponse (c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449:48)
    at processMessageQueue (c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:276:17)
    at Immediate.<anonymous> (c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:260:13)
    at process.processImmediate (node:internal/timers:476:21) {
  code: -32601,
  data: undefined
}

Node.js v18.15.0
[Info  - 8:16:17 PM] Connection to server got closed. Server will restart.
[Error - 8:16:17 PM] Unhandled method zenScript/fsReadDirectory
c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449
                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));
                                               ^

ResponseError: Unhandled method zenScript/fsReadDirectory
    at handleResponse (c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:449:48)
    at processMessageQueue (c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:276:17)
    at Immediate.<anonymous> (c:\Users\bruno\.vscode\extensions\yesterday17.zenscript-0.2.10\node_modules\vscode-jsonrpc\lib\main.js:260:13)
    at process.processImmediate (node:internal/timers:476:21) {
  code: -32601,
  data: undefined
}

Node.js v18.15.0
[Error - 8:16:17 PM] Connection to server got closed. Server will not be restarted.

**Comment by Sethgno** [comment]
i have same issue ever since a VSC update earlier this year so maybe reverting VSC version would fix but idk i havnt tried. if anyone wants something else for now try this one Atishay-Jain.All-Autocomplete it only suggests things from files you have open but still useful

**Comment by Herminos** [comment]
same issue
